// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5mKuWWdjM73AqB-ZWw12xSTvMRY8fHoY',
    appId: '1:215141095629:web:7a79cd5b95e9c070053184',
    messagingSenderId: '215141095629',
    projectId: 'sharenet-earn',
    authDomain: 'sharenet-earn.firebaseapp.com',
    storageBucket: 'sharenet-earn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFp9t0nnmQtt8qLdDnwmC3R00fTcfQQtk',
    appId: '1:215141095629:android:bf62040e7739e946053184',
    messagingSenderId: '215141095629',
    projectId: 'sharenet-earn',
    storageBucket: 'sharenet-earn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbD3DLBLXg9tDkGEFlscrh8SZHW4mqeQ',
    appId: '1:215141095629:ios:69e824658d516b74053184',
    messagingSenderId: '215141095629',
    projectId: 'sharenet-earn',
    storageBucket: 'sharenet-earn.firebasestorage.app',
    iosBundleId: 'com.example.sharenetEarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIbD3DLBLXg9tDkGEFlscrh8SZHW4mqeQ',
    appId: '1:215141095629:ios:69e824658d516b74053184',
    messagingSenderId: '215141095629',
    projectId: 'sharenet-earn',
    storageBucket: 'sharenet-earn.firebasestorage.app',
    iosBundleId: 'com.example.sharenetEarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5mKuWWdjM73AqB-ZWw12xSTvMRY8fHoY',
    appId: '1:215141095629:web:0084730e662e0bd3053184',
    messagingSenderId: '215141095629',
    projectId: 'sharenet-earn',
    authDomain: 'sharenet-earn.firebaseapp.com',
    storageBucket: 'sharenet-earn.firebasestorage.app',
  );
}
